Add alpm_pkg_vercmp
dns2utf8/alpm-rs pull request #1
Opened 2016-09-18 14:09 UTC by ilpianista

This adds alpm_pkg_vercmp

2016-09-19 13:04 UTC, dns2utf8 commented on src/lib.rs
> +use std::os::raw::{c_char,c_int};
please add a space after the comma.

2016-09-19 13:07 UTC, dns2utf8 commented on src/lib.rs
> +  /// Returns a value comparable to the way strcmp works. Returns 1
Is it possible to change this part of the description to a list or a table?

2016-09-19 13:09 UTC, dns2utf8 commented on src/lib.rs
> +      Ok(pkg_vercmp(a.as_ptr() as *const c_char, b.as_ptr() as *const c_char) as i32)
Maybe we should wrap the result in [std::cmp::Ordering](https://doc.rust-lang.org/stable/std/cmp/enum.Ordering.html).

What do you think?

2016-09-19 13:09 UTC, dns2utf8 requested changes
Very cool :+1:

2016-09-19 13:13 UTC, ilpianista commented on src/lib.rs
> +      Ok(pkg_vercmp(a.as_ptr() as *const c_char, b.as_ptr() as *const c_char) as i32)
Absolutely yes! I'll do it.

2016-09-19 13:13 UTC, ilpianista commented on src/lib.rs
> +  /// Returns a value comparable to the way strcmp works. Returns 1
Mmm, sorry I don't get what you mean here.

2016-09-19 13:16 UTC, dns2utf8 commented on src/lib.rs
> +  /// Returns a value comparable to the way strcmp works. Returns 1
The line wrap was a bit confusing, but when it returns `std::cmp::Ordering` it will become shorter. This will be ok.

2016-09-21 15:22 UTC, dns2utf8 commented
Can you rebase it?

2016-09-21 15:25 UTC, dns2utf8 approved these changes

2016-09-22 07:42 UTC, merged

2016-09-22 07:45 UTC, dns2utf8 commented
Thank you :smile: